print("this is my first try on git, as well as my first python code")
print("second version test")
print("git test")
print("git test2")
print("git test3")
print("vscode git test")
print("vscode final test")
print("terminal test")
print("VS TEST23546")
print("VS code computer3 commit test")
print("SSH terminal works and VS code works in certain condition")